version: '3'
services:
  nginx:
    image: nginx:1.18-alpine
    container_name: web-server
    ports:
      - 81:80
    depends_on:
      - php
    volumes:
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/conf:/etc/nginx/conf.d
    working_dir: /var/www/app

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: view
    volumes:
      - ./app:/var/www/app
    depends_on:
      - db
    restart: always
    tty: true

  db:
    image: mysql:5.7
    restart: always
    container_name: app-db
    environment:
      - MYSQL_ROOT_PASSWORD=wrg9enfX
      - MYSQL_DATABASE=view_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=aVhvwz0v
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.conf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306